helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/templates/deployment-repository.yaml, helm/alfresco-content-services/values.yaml
=> REPO-3309: add the clustering with 2 repository nodes as the default

helm/alfresco-content-services/templates/deployment-alfrescopdfrenderer.yaml, helm/alfresco-content-services/templates/deployment-imagemagick.yaml, helm/alfresco-content-services/templates/deployment-libreoffice.yaml, helm/alfresco-content-services/templates/deployment-repository.yaml, helm/alfresco-content-services/templates/deployment-share.yaml, helm/alfresco-content-services/templates/deployment-solr.yaml, helm/alfresco-content-services/values.yaml
=> REPO-3439: remove all references to quay but allow private docker repos to be set as parameters

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
* Add deployment.method JAVA_OPTS to docker-compose and helm to be picked up by the Heartbeat InfoDataCollector
=> REPO-3329: Record deployment method

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
* Update docker-compose with released Content Repository 6.0.0
* Update docker-compose and Helm chart with released Share 6.0
=> Update versions of content repository and Share

helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/templates/NOTES.txt, helm/alfresco-content-services/templates/Rule_04-network-policy-repository.yaml, helm/alfresco-content-services/templates/Rule_05-network-policy-search.yaml, helm/alfresco-content-services/templates/Rule_10-network-policy-zeppelin.yaml, helm/alfresco-content-services/values.yaml
SEARCH-825 (Create a helm chart for Alfresco Zeppelin)
=> SEARCH-825 (Create a helm chart for Alfresco Zeppelin) (#28)

docs/helm-deployment-minikube.md
See https://github.com/Alfresco/acs-deployment/issues/44
=> Update minikube documentation

README.md
We should make clear that these charts are not designed to be used as-is.
=> Added section about custom infrastructures

docs/helm-deployment-aws_cloud.md
- added hint to use EKS instead of Kops
- added note about configuring Kops after getting feedback
=> Clarify Kops configuration

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
Further changes to Helm charts will be done in https://issues.alfresco.com/jira/browse/REPO-3682
=> REPO-3679 Add ActiveMQ to docker-compose

README.md, docker-compose/docker-compose.yml, docs/docker-compose-deployment.md, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
docker-compose.yml
Charts.yaml
README.md
=> REPO-3747 update trial license usage info

helm/alfresco-content-services/templates/ingress-repository.yaml, test/postman/acs-test-collection.json
- forbid more urls
- add postman tests
=> REPO-3802 Unprotected access to Solr APIs

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- updated versions for router and transformers
=> ATS-156 : Release ATS 0.1.1-EA (including T-Engines 2.0.1-EA)

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- updated versions for router, transformers and store
=> ATS-140 : Release ATS 0.2-EA for ACS 6.1.0-EA3

README.md, docs/docker-compose-deployment.md, docs/helm-deployment-aws_cloud.md
* Added 'docker login quay.io' for Docker Compose steps
* Added new section for Helm deployment - 'Creating a Docker registry pull secret'
* Updated Helm steps to include 'quay-registry-secret'
=> DOCS-5103 Add Quay.io access

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
Reverts Alfresco/acs-deployment#90
=> Revert "ATS-140 : Release ATS 0.2-EA for ACS 6.1.0-EA3"

docs/docker-compose-deployment.md
Now that we have introduced a proxy for ADW, the ports have changed
=> Adopt ports in documentation to latest changes

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- upgraded T-Engines to 2.0.6-RC
=> ATS-198 : ACE-5893: Files bigger than 1MB can not be uploaded via multipart API

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
=> ATS-194 : Release ATS 0.4.0-RC (~ target ACS 6.1.0 RC2)

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
=> REPO-4031 Release Shared File Store 0.5

docs/helm-deployment-aws_kops.md
The docs got slightly out of date in some parts.
The k8s dashboard instructions are not applicable in the same way any more and there is a better description inside their repository, so I propose to just redirect there for any specific information.
=> Update documentation for KOPS deployment

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- update T-Router and T-Engines versions in values.yaml and docker-compose.yml
=> ATS-230: Release ATS 1.0.0 (~ target ACS 6.1.0 RC6)

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- PRs in acs-deployment for Share 6.1.0
=> SHA-2272 : Finish Release Process For Share 6.1.0

docker-compose/docker-compose.yml, helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/values.yaml, test/postman/helm/acs-test-helm-collection.json
Upgrade to Alfresco Digital Workspace 1.1.0.
- update application image to 1.1.0
- update proxy image to 3.0.0
=> [ACA-2293] upgrade ADW to 1.1.0

docs/customising-deployment.md, docs/docker-compose-deployment.md, docs/helm-deployment-acs-with-ai.md
- use relative URLs to project files
-  use https links to online Documentation
=> DOCS-5309 Use relative URLs in project files

helm/alfresco-content-services/templates/ingress-repository.yaml
Added prometheus to be properly blocked by ngnix proxy.
=> REPO-4398 : prometheus is properly blocked

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
=> ATS-490 : ATS: T-Engines - release 2.1.0-RC1

helm/alfresco-content-services/templates/config-transform-router.yaml, helm/alfresco-content-services/templates/config-transformer-routes.yaml
- rename ai routes file
- update the ai routes
- rename the route file location env variable
- remove unnecessary 'SPRING_APPLICATION_JSON' env variable
=> ATS-405: Update AI engine configuration for ATS 1.1

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
- PR for Share 6.1.1-RC1 in acs-deployment
=> SHA-2323 : Prepare for 6.1.1 release

helm/alfresco-content-services/requirements.yaml
Bamboo job completed successfully
https://bamboo.alfresco.com/bamboo/browse/PLAT-ACSHELM215-1
=> SEARCH-1661 New Search helm chart release

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
- PR for Share 6.1.1-RC2 in deployment
=> MNT-20840: Update Share to 6.1.1-RC2

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
=> Changes to pick up ACS 6.2.0-A7

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
=> SHA-2330 : Create RC for 6.2

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
Please wait from the 6.2.0-RC1 release to have taken place before merging to master.
=> ACS 6.2.0-RC1

helm/alfresco-content-services/templates/Rule_04-network-policy-repository.yaml, helm/alfresco-content-services/templates/Rule_11-network-policy-transform-router.yaml, helm/alfresco-content-services/values.yaml
* Add missing network policies for repo/ transform router communication
=> REPO-4672: Add network policies for transform router

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
=> SHA-2339 :  Create Share 6.1.1 Final Release Build

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
=> ATS-576: ATS: T-Engines - release 2.1.0-RC3

helm/alfresco-content-services/values.yaml
Once this PR is merged we'll also cherry-pick the commit into the `support/SP/3.N` branch.
=> ATS-571: Release Intelligence Services (AIS) 1.1.0-RC3

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
- Share 6.1.1.1 HF containing the fix
=> Update to Share 6.1.1.1 HF

docker-compose/docker-compose.yml, helm/alfresco-content-services/requirements.yaml
https://bamboo.alfresco.com/bamboo/browse/PLAT-ACSHELM244-5
=> SEARCH-1879 - Updating Search chart and image 1.4.0

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
=> SHA-2349 : Release Share 6.2

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
=> ATS-440 : ATS: T-Engines - release 2.1.0

docker-compose/docker-compose.yml, helm/alfresco-content-services/requirements.yaml
update sync service to 3.2.0
update sync service helm to 2.0.0
=> APPSREPO-709:release sync service 3.2.0 and helm 2.0.0

helm/alfresco-content-services/values.yaml
Once reviewed & merged, this commit will  be cherry-picked into the **support/SP/3.N** branch.
=> ATS-516: Release Intelligence Services (AIS) 1.1.0

docker-compose/docker-compose.yml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/values.yaml
* Updated to use ADW 1.3.0-beta for the SSO validation
=> ACA-2779 prepare ACS helm chart release

helm/alfresco-content-services/Chart.yaml
- update chart version for future releases
=> REPO-4661: Increment chart version for next release (3.0.3)

helm/alfresco-content-services/values.yaml
=> ATS-612 : AI-CE: Release Intelligence Services (AIS) 1.1.1-RC1

helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
=> ATS-613 : AI-CE: "Engineering Release" of AIS 1.1.1 (for ACS 6.2.x)

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- update shared file store version to 0.6.0
=> REPO-4751: Upgrade to Spring 5.2

docker-compose/docker-compose.yml, helm/alfresco-content-services/requirements.yaml
and update helm chart from 2.0.0 to 3.0.1
=> APPSREPO-752 bumb sync service from 3.2.0 to 3.3.1

helm/alfresco-content-services/values.yaml
=> ATS-651 : AIS: Release Intelligence Services 1.1.2

helm/alfresco-content-services/templates/config-repository.yaml
- Removed JAVA_OPTS `-Dcsrf.filter.enabled=false` for email configuration
=> MNT-20671 - Remove csrf filter for email

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
T-Engine - 2.2.1
T-Router - 1.2.0
SFS - 0.7.0
=> ATS-700 ATS-743 Update Transformers

docker-compose/docker-compose.yml, helm/alfresco-content-services/requirements.yaml
update master with sync service 3.3.2 and helm chart 3.0.3
=> update sync service to 3.3.2 and helm chart to 3.0.3

docs/helm-deployment-aws_kops.md, helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/values.yaml
Removes surplus ingress deployed by infrastructure chart and remove specific ingress version from documentation.
=> ACS-16 and ACS-221: Fix ingress issues

.editorconfig, helm/alfresco-content-services/templates/deployment-ai-transformer.yaml, helm/alfresco-content-services/templates/deployment-filestore.yaml, helm/alfresco-content-services/templates/deployment-imagemagick.yaml, helm/alfresco-content-services/templates/deployment-libreoffice.yaml, helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml, helm/alfresco-content-services/templates/deployment-repository.yaml, helm/alfresco-content-services/templates/deployment-share.yaml, helm/alfresco-content-services/templates/deployment-tika.yaml, helm/alfresco-content-services/templates/deployment-transform-misc.yaml, helm/alfresco-content-services/templates/deployment-transform-router.yaml
launch with helm 2.14 which uses the kubectl 1.14 lib:
Error: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "limits" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "requests" in io.k8s.api.core.v1.Probe]
=> fixed validation error on resources with helm-2.14/kubectl-1.14

helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/templates/config-ai-transformer.yaml, helm/alfresco-content-services/templates/config-imagemagick.yaml, helm/alfresco-content-services/templates/config-libreoffice.yaml, helm/alfresco-content-services/templates/config-pdfrenderer.yaml, helm/alfresco-content-services/templates/config-repository.yaml, helm/alfresco-content-services/templates/config-tika.yaml, helm/alfresco-content-services/templates/config-transform-misc.yaml, helm/alfresco-content-services/templates/config-transform-router.yaml, helm/alfresco-content-services/templates/pvc.yaml, helm/alfresco-content-services/values.yaml
=> infra chart removing

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
- acs-deployment PR for Share 6.2.2-RC1
=> APPS-203 : Create Share 6.2.2-RC1

helm/alfresco-content-services/ai-reference-values.yaml
- update alfresco-content-repository-aws version
=> ACS-249: Service Pack: Create RC1/A Release for ACS 6.2.2

docker-compose/docker-compose.yml, helm/alfresco-content-services/ai-reference-values.yaml, helm/alfresco-content-services/values.yaml
- acs-deployment PR for Share 6.2.2 release
=> APPS-229 : Create Share 6.2.2 Final Build

docker-compose/docker-compose.yml, helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/values.yaml
=> Bump 1.6.0 DW

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
- transform-router 1.3.1-A1
- transform-core-aio 2.3.2
- shared-file-store 0.9.0
=> ATS-804  & ACS-224: Update ATS 1.3.1-A1, T-Core 2.3.2 and SFS with 0.9.0

docker-compose/docker-compose.yml, helm/alfresco-content-services/values.yaml
Contains update to base java image 11.0.7-openjdk-centos-7-dcd8edf6cb70
=> ATS-814 Update SFS to 0.10.0

helm/alfresco-content-services/requirements.yaml
Update ADF app chart, see AAE-3810
=> [AAE-3810] fix ADF app when mounted on root context

README.md, docs/docker-compose/README.md, docs/docker-compose/examples/customisation-guidelines.md, docs/helm/eks-deployment.md, docs/helm/examples/customisation-guidelines.md, docs/helm/examples/email-enabled.md, docs/helm/examples/search-external-access.md, docs/helm/examples/with-ai.md, docs/helm/examples/with-aws-services.md, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/templates/NOTES.txt, helm/alfresco-content-services/charts/alfresco-search/templates/NOTES.txt
Updated documentation ready for the 5.0.0-M1 chart to be in stable.
Also fixed some other documentation issues noticed recently.
=> OPSEXP-562: Updated documentation

.travis.yml
Just adding a check to the deploy test so that all tests get run when we publish a chart.
=> Release 5.0.0-M1 chart

.travis.yml
replaced custom tool install lines with shared configs
=> OPSEXP-586 use shared travis config

.travis.yml, docker-compose/6.2.N-docker-compose.yml, helm/alfresco-content-services/6.2.N_values.yaml
* Add fix branches to trigger travis builds
* Images are being pulled from quay.io
=> MNT-21967 MNT-21800 - Update ACS to v6.2.2.5

docs/helm/docker-desktop-deployment.md, docs/helm/eks-deployment.md
- in particular using local k8s cluster via Docker Desktop
- add ingress-ngnix chart
- add a troubleshooting tip
=> Minor updates to readme(s) for helm / kubernetes

docs/properties-reference.md
* Addition of new properties to md reference file
Build was killed as this is just doc change.
=> ACS-940 Alfresco Documentation for the query accelerator

docker-compose/6.1.N-docker-compose.yml, docker-compose/6.2.N-docker-compose.yml, docker-compose/community-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/charts/activemq/values.yaml
See [ACS-1185](https://alfresco.atlassian.net/browse/ACS-1185)
=> ACS-1185 Update activemq images to 5.16.1/ 5.15.14

docker-compose/community-docker-compose.yml, docker-compose/docker-compose.yml, docs/helm/examples/with-aws-services.md, helm/alfresco-content-services/community_values.yaml, helm/alfresco-content-services/values.yaml
Upgraded to PostgreSQL 13.1 in ACS 7.0.0
=> ACS-1183 ACS 7 Stacks: PostgreSQL

docker-compose/community-docker-compose.yml
Fix for https://github.com/Alfresco/acs-deployment/issues/490
=> OPSEXP-805: Increased connection timeout for repo to search communication

docker-compose/docker-compose.yml, helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml, helm/alfresco-content-services/requirements.yaml
Bumb Sync Service to 3.4.0 and helm chart to 3.0.8  
Committer: Chelaru Ciprian <chelaru.ciprian@ness.com>
=> Bumb Sync Service to 3.4.0 and helm chart to 3.0.8

README.md, docker-compose/6.2.N-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/6.2.N_values.yaml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/values.yaml
Update ADW image to 2.1.0-adw and pull SFS image from quay.io
=> OPSEXP-840 and OPSEXP-842

.pre-commit-config.yaml, helm/alfresco-content-services/6.1.N_values.yaml, helm/alfresco-content-services/6.2.N_values.yaml, helm/alfresco-content-services/requirements.yaml, helm/alfresco-content-services/values.yaml
switch to common chart as per AAE-4349 since deprecation of adf one which has not been released in M12
=> AAE-4349 Use activiti common chart

.travis.yml, helm/alfresco-content-services/values.yaml
Added function in the travis build that prints the logs of failed pods
=> OPSEXP-508: Log access

helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/values.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/README.md
Run pre-commit hook to include new properties from values files.
NOTE: Had to add a blank line to search values file to avoid incorrect docs generation.
=> Fix pre-commit hook failure

.travis.yml
add the 'latest' tag to pushed released (follow version tag)
refs OPSEXP-907
=> OPSEXP-907 add tagging 'latest' skipci

docs/helm/examples/with-ms-teams.md, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-ms-teams-service.tpl, helm/alfresco-content-services/templates/config-ms-teams-service.yaml, helm/alfresco-content-services/templates/deployment-ms-teams-service.yaml, helm/alfresco-content-services/templates/ingress-ms-teams-service.yaml, helm/alfresco-content-services/templates/svc-ms-teams-service.yaml, helm/alfresco-content-services/values.yaml
- passed pre-commit hooks
- sanity checked ms-teams-service pod startup (in local k8s)
- note: will fully test in https pipeline env
=> ACS-1870: add new MS Teams option

helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
- follow-on to https://github.com/Alfresco/acs-deployment/pull/593
=> ATS-958: Bump ATS 1.4.1-A3 (from 1.4.0)

docker-compose/6.1.N-docker-compose.yml, docker-compose/6.2.N-docker-compose.yml, docker-compose/7.0.N-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/6.2.N_values.yaml, helm/alfresco-content-services/7.0.N_values.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
Includes:
- ATS-967 SFS to 0.16.0
- ATS-966 AIS to 1.4.0
- ACS-1967 OOI to 1.1.1
=> ATS-964 Bump ATS 1.4.1

.travis.yml, docker-compose/6.2.N-docker-compose.yml, docker-compose/7.0.N-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/6.2.N_values.yaml, helm/alfresco-content-services/7.0.N_values.yaml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml, helm/alfresco-content-services/values.yaml
fix adw 2.4.0 search isue and revert syncservice to GA version
=> OPSEXP-1117 update images for 5.1.1 release

docs/docker-compose/README.md
=> Improve docs

docker-compose/docker-compose.yml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml, helm/alfresco-content-services/values.yaml
=> DESKTOPAPP-847: Bump Sync Service from 3.5.0-A4 to 3.5.0

docker-compose/docker-compose.yml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/values.yaml, helm/alfresco-content-services/values.yaml
=> ACS-2307 Update SS/IE to 2.0.3-RC4

docker-compose/6.1.N-docker-compose.yml, docker-compose/6.2.N-docker-compose.yml, docker-compose/7.0.N-docker-compose.yml, docker-compose/7.1.N-docker-compose.yml, docker-compose/community-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/activemq/Chart.yaml, helm/alfresco-content-services/charts/activemq/README.md, helm/alfresco-content-services/charts/activemq/values.yaml, helm/alfresco-content-services/charts/alfresco-search/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml
=> OPSEXP-1035 Updated ActiveMQ to 5.16.4

.pre-commit-config.yaml, .travis.yml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/activemq/README.md, helm/alfresco-content-services/charts/activemq/values.yaml, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/values.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml, helm/alfresco-content-services/values.yaml
* update alfresco-ai-docker-engine
* align busybox version and update to 1.35.0
=> ACS-2671 Update alfresco-ai-docker-engine to 1.4.2

.gitignore, .pre-commit-config.yaml, .travis.yml
=> OPSEXP-1348 use ACS_VERSION for build stages

helm/alfresco-content-services/templates/ingress-ms-teams-service.yaml, helm/alfresco-content-services/templates/ingress-ooi-service.yaml
=> OPSEXP-1374: Fix ooi and ms teams service - http 404 error

helm/alfresco-content-services/Chart.yaml
=> OPSEXP-1388 Make alfresco-search inclusion configurable

helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml, helm/alfresco-content-services/charts/alfresco-search/values.yaml
=> OPSEXP-936 Fix solr pod recreation

docker-compose/community-docker-compose.yml
OPSEXP-1528 changes for content app image in community docker compose
=> OPSEXP-1528 Docker compose community edition can be deployed without logging in to quay.io

.github/workflows/verify.yml
Skip the login of Quay.io for community build.
=> OPSEXP-1530: community builds

helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/alfresco-search/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/README.md
as per https://github.com/bitnami/charts/issues/10539#issuecomment-1161885997
=> OPSEXP-1500: apply bitnami definitive resolution

.github/workflows/verify.yml
=> OPSEXP-1547 Use upstream organization secrets

helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
Bump for onedrive 1.1.3 version.
Bump for ms-teams-integration 1.1.0 version.
=> ACS-3179, ACS-3243: Bump MS  365/OneDrive and MS Teams "sample" (helm chart)

docs/helm/examples/with-aws-services.md, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/activemq/Chart.yaml, helm/alfresco-content-services/charts/activemq/README.md, helm/alfresco-content-services/charts/activemq/templates/_helpers.tpl, helm/alfresco-content-services/charts/alfresco-content-common/templates/_helpers-activemq.tpl, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/templates/config-syncservice.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml, helm/alfresco-content-services/templates/config-repository.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-1587: Sync service to use external URL for ActiveMQ

docs/helm/examples/with-aws-services.md
=> OPSEXP-1627 Document how to deploy with Amazon Opensearch

.github/workflows/verify.yml, CONTRIBUTING.md
=> OPSEXP-1657 Fix pull requests coming from forked repos

.github/workflows/verify.yml
=> OPSEXP-1657 Fix pr coming from forked repos

.github/scripts/helm_install.sh, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-1575: move PGDATA away from efs default volume claim

README.md, docs/helm/eks-deployment.md, docs/helm/storage.md
=> OPSEXP-1575: add postgresql persistence guidance after config change

.github/workflows/community-compose.yml, .github/workflows/enterprise-compose.yml, .github/workflows/verify.yml, .pre-commit-config.d/compose.yaml, .pre-commit-config.d/helm.yaml
=> OPSEXP-1746: split docker-compose workflows

docs/helm/examples/with-aws-services.md
* Rename the placeholder to be more explicit that we want an hostname and not an URL
=> More clear elasticsearch host docs

helm/alfresco-content-services/templates/_helpers-elasticsearch.tpl, helm/alfresco-content-services/templates/config-repository.yaml, helm/alfresco-content-services/tests/search_test.yaml
=> OPSEXP-1766: fix ES protocol Issue

.github/workflows/helm-enterprise.yml
requires https://github.com/Alfresco/alfresco-build-tools/pull/144
OPSEXP-1777
=> OPSEXP-1777 Proper cleanup for helm enteprise jobs

.github/workflows/helm-enterprise.yml
Otherwise we eat cluster resources and trigger race conditions pretty easily
=> Limit concurrency in helm enterprise jobs

helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-config.yaml, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-config.yaml, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/liveindexing_test.yaml, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/values/external.yaml, helm/alfresco-content-services/tests/activemq_test.yaml, helm/alfresco-content-services/tests/alfresco-common_test.yaml, helm/alfresco-content-services/tests/search_test.yaml
=> OPSEXP-1811: fix alf-ES config

.github/workflows/docker-compose-community.yml, .github/workflows/docker-compose-enterprise.yml, .github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml, .github/workflows/pre-commit-compose.yml, .github/workflows/pre-commit-helm.yml, helm/alfresco-content-services/templates/config-repository.yaml
=> OPSEXP-1776: remove warning noise about unreachable local transformer

helm/alfresco-content-services/templates/_helpers-url.tpl, helm/alfresco-content-services/templates/config-repository.yaml, helm/alfresco-content-services/templates/config-share.yaml, helm/alfresco-content-services/tests/repository_test.yaml, helm/alfresco-content-services/tests/share_test.yaml
=> OPSEXP-1805 Make an url builder function to be dry in repo and share cm

.vscode/tasks.json
⌘ + ⇧ + P and `Tasks: Run Test Task`
speeds up running tests locally
=> Add test task for vscode editors

.github/workflows/helm-enterprise.yml
=> OPSEXP-1796 Fixup publish job

.github/workflows/helm-enterprise.yml
OPSEXP-1796
https://github.com/Alfresco/acs-deployment/actions/runs/3480549395/jobs/5820559636
=> OPSEXP-1796 Fixup publish-chart arguments

README.md, docs/helm/docker-desktop-deployment.md
- Fixed some typo
- Added the note to disable Traefik to install NGINX on Rancher Desktop.
- Updated the version of nginx used in the documentation
=> Updated the documentation with the configuration for Rancher Desktop

README.md
=> OPSEXP-1901 Document manual release steps - waiting for automation

helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/config-repository.yaml, helm/alfresco-content-services/templates/deployment-repository.yaml, helm/alfresco-content-services/templates/secret-repository.yaml, helm/alfresco-content-services/tests/activemq_test.yaml, helm/alfresco-content-services/tests/deployment-repository_test.yaml, helm/alfresco-content-services/tests/pv-repository_test.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-1651 Use existing secret to configure repo admin password

docs/helm/examples/with-aws-services.md
Ref: OPSEXP-1925
Update to previous PR following: https://alfresco.slack.com/archives/CDW82KQHX/p1673860706842949
=> OPSEXP-1925: clarify EFS usage and implications of removing it

docs/helm/examples/with-aws-services.md
=> OPSEXP-1937: set max boolean clause for ES

helm/alfresco-content-services/templates/config-share.yaml, helm/alfresco-content-services/tests/config-share_test.yaml
=> OPSEXP-1942 Fix duplicated key in share configmap

docs/helm/README.md, docs/helm/docker-desktop-deployment.md, docs/helm/eks-deployment.md, docs/helm/registry-authentication.md
=> OPSEXP-139 Document custom images overrides

.github/workflows/helm-community.yml, helm/alfresco-content-services/templates/deployment-filestore.yaml
Ref: OPSEXP-1942
Requires: https://github.com/Alfresco/alfresco-build-tools/pull/220
=> OPSEXP-1942 Add helm-template-yamllint action

helm/alfresco-content-services/templates/deployment-repository.yaml, helm/alfresco-content-services/tests/deployment-repository_test.yaml
=> OPSEXP-1963: add back volumes mounts and add tests

helm/alfresco-content-services/community_values.yaml
Required by https://github.com/Alfresco/acs-deployment/pull/867
Ref: OPSEXP-1957
=> OPSEXP-1957 Fix missing tags in community values

README.md, helm/alfresco-common/Chart.yaml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/activemq/Chart.yaml, helm/alfresco-content-services/charts/activemq/README.md, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/Chart.yaml, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md, helm/alfresco-content-services/charts/alfresco-search/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/values.yaml, helm/alfresco-content-services/charts/alfresco-search/values.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-1958 Release 5.4.0-M2

.github/workflows/bumpVersions.yml
=> OPSEXP-1958 Do not run updatecli workflow on tags and on master

README.md
=> OPSEXP-1958 Improve release README

helm/alfresco-common/Chart.yaml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/activemq/Chart.yaml, helm/alfresco-content-services/charts/activemq/README.md, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/Chart.yaml, helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md, helm/alfresco-content-services/charts/alfresco-search/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md, helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml, helm/alfresco-content-services/charts/alfresco-sync-service/README.md
=> OPSEXP-1958 prepare for next iteration

docs/helm/docker-desktop-deployment.md
=> Add missing tracking secret in community docker desktop helm docs

helm/alfresco-content-services/templates/deployment-repository.yaml, helm/alfresco-content-services/tests/deployment-repository_test.yaml
=> OPSEXP-2002 Fixup volume handling when using external database

docs/helm/eks-deployment.md, docs/helm/examples/with-aws-services.md
=> OPSEXP-1881 Update docs for the new EBS CSI driver

helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/charts/alfresco-search/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/README.md, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/Chart.yaml, helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin/README.md
=> OPSEXP-2028 Update development version

docs/helm/values/local-dev-values.yaml
=> OPSEXP-2013 fixup postgresql resources example

docker-compose/7.0.N-docker-compose.yml, docker-compose/7.1.N-docker-compose.yml, docker-compose/7.2.N-docker-compose.yml, docker-compose/7.3.N-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/7.0.N_values.yaml, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml
=> DESKTOPAPP-1615: fix versioning that do not follow the support matrix

.github/workflows/docker-compose-community.yml, .github/workflows/docker-compose-enterprise.yml, .github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml, .github/workflows/helm-release.yml, .github/workflows/helm-static-checks.yml, .github/workflows/pre-commit-compose.yml, .github/workflows/pre-commit-helm.yml
=> OPSEXP-2109 Update alfresco-build-tools actions

README.md
* Add release badge
Ref: OPSEXP-2109
=> OPSEXP-2109 Fixup typos in README

.github/workflows/docker-compose-community.yml, .github/workflows/docker-compose-enterprise.yml, .github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml, .github/workflows/helm-static-checks.yml, .github/workflows/pre-commit-compose.yml, .github/workflows/pre-commit-helm.yml, .pre-commit-config.yaml, README.md
=> OPSEXP-2130 Support release branches in GHA workflows

docker-compose/community-docker-compose.yml
=> OPSEXP-2168 Add control center to community docker-compose

helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
Refs: OPSEXP-2174
Thanks to https://github.com/Alfresco/acs-deployment/pull/958/commits/ab7d5be732617e2a3febf6aade3acc2ddc5e7286 and https://github.com/Alfresco/acs-deployment/pull/958/commits/5f6f8da994cfa363ac3e8d5b97dbe7449be2b92d
=> OPSEXP-2174 Fixup alfresco-search and sync tags not properly applied

docker-compose/community-docker-compose.yml
Ref: OPSEXP-2174
Generated from https://github.com/Alfresco/acs-deployment/pull/967
=> OPSEXP-2174 Bump content-app, control-center, tengine-aio in community compose

docker-compose/7.4.N-docker-compose.yml, docker-compose/docker-compose.yml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2174 Fix workspace 4.1 login on helm chart and compose

docker-compose/docker-compose.yml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2193 Fix workspace 4.0.0 login on helm and compose

.github/workflows/bumpVersions.yml, updatecli-matrix-targets.yaml
Ref: OPSEXP-2174
Requires https://github.com/Alfresco/alfresco-updatecli/pull/4
=> OPSEXP-2174 Fixup acc and adw in community docker compose

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2174 Bump chart dependencies

README.md, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2174 Prepare for 6.1.0-M.1 release

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-ats.tpl
=> OPSEXP-2205: bump ATS charts to 0.1.1

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-1818 Bump activemq chart to 3.2.0

updatecli-matrix-targets.yaml
Ref: OPSEXP-2214
Not solving the issue but at least config is consistent
=> OPSEXP-2214 Fixup updatecli helm keys

.github/workflows/bumpVersions.yml, helm/alfresco-content-services/7.0.N_values.yaml, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/community_values.yaml, helm/alfresco-content-services/values.yaml, updatecli-matrix-targets.yaml
Ref: OPSEXP-2214
See https://github.com/updatecli/updatecli/issues/1332
Plus some random cleanup of mess around values files.
=> OPSEXP-2214 Remove anchors in values files which are causing issues with updatecli

.github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml
Ref: OPSEXP-2221
Ref: OPSEXP-2222
this is an initial work to test the very basic functionality of the new self hosted runners
=> OPSEXP-2221 Switch to self hosted runners for helm integration tests

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, updatecli.d/helm-autodiscovery.yaml
=> OPSEXP-2235 Update helm dependencies

.github/workflows/docker-compose-enterprise.yml
=> OPSEXP-2257 Dynamic matrix for docker compose testing

README.md, docs/helm/values/local-dev-values.yaml, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2235 Prepare for 7.0.0-M.1 release

helm/alfresco-content-services/7.0.N_values.yaml, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/community_values.yaml
=> OPSEXP-2235 fixup header comment for values files

docker-compose/community-docker-compose.yml
=> OPSEXP-2273 Fixup docker compose community top comments

.github/workflows/helm-release.yml
=> OPSEXP-1908 ensure no deps are pre-release at release time

.github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/config-database.yaml, helm/alfresco-content-services/tests/config-database_test.yaml, helm/alfresco-content-services/values.yaml
Ref: OPSEXP-2177
* Introduce support for generic database in search enterprise
=> OPSEXP-2177 Integrate alfresco-search-enterprise v2.0.0-alpha.0

README.md, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2311 Prepare for 7.0.0-M.2 release

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2339: bump alfresco-repository chart

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/config-infrastructure.yaml
=> OPSEXP-2297: bump alfresco-repository dependency

README.md
=> OPSEXP-2365 Update release docs

.pre-commit-config.yaml, README.md, docs/helm/desktop-deployment.md, docs/helm/eks-deployment.md, docs/helm/examples/with-ai.md, docs/helm/examples/with-aws-services.md, docs/helm/examples/with-ms-teams.md, docs/helm/examples/with-ooi.md
=> OPSEXP-2365 Update docs for v7.0.0

docker-compose/7.1.N-docker-compose.yml, docker-compose/7.2.N-docker-compose.yml, docker-compose/7.3.N-docker-compose.yml, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml
=> OPSEXP-2403 Bump ATS and Sync tags in 7.3/7.2/7.1 to fix activemq CVE-2023-46604

README.md, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2435 Bump Search Enterprise chart to v3.0.3

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2299: use latest alfresco-share chart 0.3.0

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-message-broker.tpl, helm/alfresco-content-services/templates/config-infrastructure.yaml, helm/alfresco-content-services/tests/config-infra_test.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-2293: bump alfresco-ai-transformer

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2293 Bump alfresco-ai-transformer dependency

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-ats.tpl, helm/alfresco-content-services/templates/config-infrastructure.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-2301 Bump alfresco-transform-service chart to 1.0.0-alpha.2

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-database.tpl, helm/alfresco-content-services/templates/config-infrastructure.yaml, helm/alfresco-content-services/templates/secret-sync-database.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-2300: bump alfresco-sync-service chart to 5.0.0-alpha.1

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2295 Bump alfresco-connector-ms365 chart to 0.5.0-alpha.0

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2324: allow for embeded pg sync to cope with more replicas and rolling upgrade scenarios

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-search.tpl, helm/alfresco-content-services/templates/config-infrastructure.yaml, helm/alfresco-content-services/templates/secret-search.yaml, helm/alfresco-content-services/tests/config-infra_test.yaml, helm/alfresco-content-services/tests/search_test.yaml
=> OPSEXP-2291 Bump alfresco-search to 3.0.0-alpha.0

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2445 Bump AI Transformer chart to 1.0.0

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2452 Bump share chart to support clustering

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml
=> OPSEXP-2391 Fix alfresco control center condition

updatecli.d/helm-autodiscovery.yaml
=> OPSEXP-2449 Skip sso example chart in updatecli pipeline

.github/workflows/helm-community.yml, .github/workflows/helm-release.yml
* drop unnecessary wait before retryable step
* simplify publishing of the single umbrella chart
Ref: OPSEXP-2392
=> OPSEXP-2392 Simplify helm workflows

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
!Ref OPSEXP-2545
https://github.com/Alfresco/alfresco-helm-charts/pull/230
=> OPSEXP-2454 Bump sync chart to support clustering

README.md
=> OPSEXP-2460: update README to reflect new release policy

.github/workflows/helm-enterprise.yml, helm/acs-sso-example/Chart.lock, helm/acs-sso-example/Chart.yaml, helm/acs-sso-example/README.md, helm/acs-sso-example/docs/sso-guide.md, helm/acs-sso-example/values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2502 Switch to the new adf app chart

README.md, docker-compose/7.1.N-docker-compose.yml, docker-compose/7.2.N-docker-compose.yml, docker-compose/7.3.N-docker-compose.yml, docker-compose/7.4.N-docker-compose.yml, docker-compose/community-docker-compose.yml, docker-compose/docker-compose.yml, docker-compose/pre-release-docker-compose.yml, docker-compose/solr6-override-docker-compose.yml, docs/helm/upgrades.md, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/community_values.yaml, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-2518: bump component for 8.0.0 release

docs/helm/kind-deployment.md
Fixing indentation from https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster
=> Fix kind create cluster snippet in kind-deployment.md

docker-compose/docker-compose.yml, docker-compose/pre-release-docker-compose.yml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-2574 Bump component for 8.0.1 release

.github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml
=> OPSEXP-2614 Bump kind to support EKS 1.28

.github/workflows/docker-compose-enterprise.yml, .github/workflows/helm-enterprise.yml, docker-compose/7.1.N-docker-compose.yml, docker-compose/7.2.N-docker-compose.yml, docker-compose/7.3.N-docker-compose.yml, docker-compose/7.4.N-docker-compose.yml, docker-compose/community-docker-compose.yml, docker-compose/docker-compose.yml, docker-compose/pre-release-docker-compose.yml, docker-compose/solr6-override-docker-compose.yml, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/community_values.yaml, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
Ref: OPSEXP-2629
requires https://github.com/Alfresco/alfresco-updatecli/pull/34
=> OPSEXP-2629 Bump charts and tags for Fornax release

docker-compose/docker-compose.yml
=> OPSEXP-2633 Revert sync to 4.0.1

docker-compose/7.1.N-docker-compose.yml, docker-compose/7.2.N-docker-compose.yml, docker-compose/7.3.N-docker-compose.yml, docker-compose/7.4.N-docker-compose.yml, docker-compose/docker-compose.yml, docker-compose/pre-release-docker-compose.yml, helm/alfresco-content-services/7.1.N_values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
* OPSEXP-2651: https://github.com/Alfresco/alfresco-updatecli/pull/36
* OPSEXP-2650: https://github.com/Alfresco/alfresco-updatecli/pull/35
=> OPSEXP-2651 Update values for compose and helm charts after compatibility matrix fixes

helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2651 Release alfresco-content-services v8.1.1 chart

docs/helm/eks-deployment.md
=> OPSEXP-2608 Migrate helm diagrams to mermaid

docker-compose/7.2.N-docker-compose.yml, docker-compose/7.3.N-docker-compose.yml, docker-compose/7.4.N-docker-compose.yml, docker-compose/community-docker-compose.yml, docker-compose/docker-compose.yml, docker-compose/pre-release-docker-compose.yml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-2677 Bump tags for Gemini release

helm/acs-sso-example/values.yaml
=> OPSEXP-2668 Bump to keycloak 24.0.5

docker-compose/docker-compose.yml
=> OPSEXP-2698: add strict ordering of repo/search components

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2785 Bump connector charts adding completely customizable probes

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2504 Change default strategy for filestore deployment

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
ref: OPSEXP-2482
* https://github.com/Alfresco/alfresco-helm-charts/pull/371
* https://github.com/Alfresco/alfresco-helm-charts/pull/375
=> OPSEXP-2482 Bump charts versions

helm/alfresco-content-services/templates/_helpers-database.tpl, helm/alfresco-content-services/tests/config-infrastructure_test.yaml
=> Fix external postgres database handling

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2874 Revert alfresco-search-enterprise chart to latest stable version

.github/workflows/docs.yml
=> OPSEXP-2881: trigger docs publication on content change on master and releases

helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2892: fix broken mq secret for enterprise search

.github/workflows/helm-enterprise.yml, helm/alfresco-content-services/pre-release_values.yaml
=> OPSEXP-2913 Re-enable testing renditions for pre-release helm charts

docs/helm/README.md, docs/helm/desktop-deployment.md, docs/helm/eks-deployment.md
=> OPSEXP-2410 Add instruction to install with helm older version of ACS on main helm readme

helm/acs-sso-example/Chart.lock, helm/acs-sso-example/Chart.yaml, helm/acs-sso-example/README.md, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-2900 Bump charts dependencies

docker-compose/7.1.N-compose.yaml, docker-compose/7.2.N-compose.yaml, docker-compose/7.3.N-compose.yaml, docker-compose/7.4.N-compose.yaml, docker-compose/community-compose.yaml, docker-compose/compose.yaml, docker-compose/pre-release-compose.yaml, docker-compose/solr6-overrides.yaml
=> OPSEXP-2968: build share URL using localhost hostname (align with CSRF conf)

helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2943 Add audit storage dtas tests

.pre-commit-config.yaml, README.md, helm/acs-sso-example/Chart.yaml, helm/acs-sso-example/README.md, helm/acs-sso-example/updatecli-matrix-targets.yaml
=> OPSEXP-2938 Bump acs-sso-example chart version

helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
Ref: OPSEXP-2988
Bump chart version
=> OPSEXP-2988: bump chart version

.github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml
=> OPSEXP-3005 Update setup-kind

.github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml, docs/helm/ingress-nginx.md, docs/helm/kind-deployment.md, helm/acs-sso-example/docs/step-by-step-guide.md
=> OPSEXP-3049 Update ingress-nginx to v1.12.0

docker-compose/7.2.N-compose.yaml, docker-compose/7.3.N-compose.yaml, docker-compose/7.4.N-compose.yaml, docker-compose/community-compose.yaml, docker-compose/compose.yaml, docker-compose/pre-release-compose.yaml, docker-compose/solr6-overrides.yaml, helm/acs-sso-example/Chart.lock, helm/acs-sso-example/Chart.yaml, helm/acs-sso-example/README.md, helm/acs-sso-example/values.yaml, helm/alfresco-content-services/7.2.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/community_values.yaml, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-3034 Bump tags for Pegasus release

docker-compose/pre-release-compose.yaml, helm/alfresco-content-services/pre-release_values.yaml
=> OPSEXP-3072 Bump elasticsearch to 8.x for pre-release

.github/workflows/helm-community.yml, .github/workflows/helm-enterprise.yml
=> OPSEXP-3029: bump KinD using newer setup-kind action

README.md, docs/index.md
=> OPSEXP-3029: bump kubernetes badges in doc to reflect EKS/KinD bump

docs/docker-compose/README.md
=> OPSEXP-3014: add missing doc for max file upload settings for compose

README.md, docs/docker-compose/README.md, docs/index.md
* announce adding anonymous volume to alfresco service
* announce leveraging extends
* improve the compose deployments docs
OPSEXP-3097
=> OPSEXP-3097 Improve compose readme and announce upcoming changes

.github/workflows/helm-static-checks.yml
https://github.com/helm-unittest/helm-unittest/releases/tag/v0.8.0
we'll look into them later
OPSEXP-3120
=> OPSEXP-3120 Pin helm-unittest version to fix the build

docs/helm/examples/with-aws-services.md
=> fix doc typo

.github/workflows/bumpVersions.yml, docker-compose/updatecli-matrix-targets.yaml, helm/acs-sso-example/updatecli-matrix-targets.yaml, helm/alfresco-content-services/updatecli-matrix-targets.yaml
=> OPSEXP-3167 Cleanup updatecli workflow

helm/acs-sso-example/Chart.lock, helm/acs-sso-example/Chart.yaml, helm/acs-sso-example/README.md, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-3128 Bump charts dependencies

helm/alfresco-content-services/templates/config-infrastructure.yaml, helm/alfresco-content-services/tests/config-infrastructure_test.yaml
=> OPSEXP-3165: fix disabling audit storage

docker-compose/23.N-compose.yaml, docker-compose/7.2.N-compose.yaml, docker-compose/7.3.N-compose.yaml, docker-compose/7.4.N-compose.yaml, docker-compose/compose.yaml, docker-compose/pre-release-compose.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
=> OPSEXP-3153: Properly disable sync service clustering

.github/workflows/download-trials-release.yml, .pre-commit-config.yaml, README.md
=> OPSEXP-3189: add a release workflow for download trials

docker-compose/community-compose.yaml, docker-compose/compose.yaml
=> OPSEXP-3189: bump postgres image tag in recent compose

helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2896 Bump dtas version

helm/alfresco-content-services/README.md, helm/alfresco-content-services/values.yaml
=> OPSEXP-2896 Bump dtas with aps fix

helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md
To incorporate:
* https://github.com/Alfresco/alfresco-helm-charts/pull/468
=> Bump alfresco-search-service chart

docs/helm/examples/with-knowledge-retrieval.md, docs/helm/values/hxi.yml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/templates/_helpers-message-broker.tpl, helm/alfresco-content-services/templates/config-infrastructure.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-3132 Add knowledge-retrieval chart as a dependency

docker-compose/hxi-overrides.yaml, docs/docker-compose/README.md
=> OPSEXP-3134 Add an HXInsight docker compose override file

.github/workflows/helm-static-checks.yml
OPSEXP-3120
Bump helm-unittest to version v1.0.0
=> OPSEXP-3120 bump helm unit test version

docker-compose/23.N-compose.yaml, docker-compose/7.3.N-compose.yaml, docker-compose/7.4.N-compose.yaml, docker-compose/community-compose.yaml, docker-compose/compose.yaml, docker-compose/pre-release-compose.yaml, helm/acs-sso-example/Chart.yaml, helm/acs-sso-example/README.md, helm/acs-sso-example/values.yaml, helm/alfresco-content-services/23.N_values.yaml, helm/alfresco-content-services/7.3.N_values.yaml, helm/alfresco-content-services/7.4.N_values.yaml, helm/alfresco-content-services/Chart.lock, helm/alfresco-content-services/Chart.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
=> OPSEXP-3455 Bump tags for Vela release

docker-compose/23.N-compose.yaml, docker-compose/compose.yaml, docker-compose/pre-release-compose.yaml, helm/alfresco-content-services/23.N_values.yaml, helm/alfresco-content-services/README.md, helm/alfresco-content-services/pre-release_values.yaml, helm/alfresco-content-services/values.yaml
=> 🛠 Updatecli pipeline values bump

docs/docker-compose/examples/config/telegraf-overrides.yaml
=> OPSEXP-3459 Remove not needed setting for jolokia

docs/docker-compose/examples/customisation-guidelines.md
Updated link to Dockerfile commands documentation.
Fix master build.
=> Fix link to Dockerfile commands reference
