Alfresco/acs-deployment

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/config-repository.yaml
- Alfresco admin password can be configurable with `helm`
- Added a `README.md` for ACS Helm charts
- Started adding ACS configuration parameters to support `helm` installation
> REPO-3479: ACS configuration values can be passed with helm command

- helm/alfresco-content-services/templates/Rule_09-network-policy-deny-k8s-dashboard.yaml
- Fixed [Rule_09-network-policy-deny-k8s-dashboard.yaml](helm/alfresco-content-services/templates/Rule_09-network-policy-deny-k8s-dashboard.yaml) to be applied globally.
> Hofix: NetworkPolicy for deny-k8s-dashboard should be global

- helm/alfresco-content-services/values.yaml
- Use alfresco-cs short name in search host
> Fix repository short name in values.yaml for search alfresco-host

- test/postman/acs-test-collection.json
Added postman integration checks for:
- Disabled `/solr` endpoint
- Blocked URI pattern of `/share` to access `alfresco` via proxy
> REPO-3596: Shut down internal APIs (Part-3)

- docs/helm-deployment-aws_cloud.md
**Limit ACS Bastion access**
- Bastion ELB Inbound to be a CIDR (user provided) for SSH connection from, and Outbound to be Bastion Host SG
- Bastion Host Inbound to be only from Bastion ELB and Outbound to: Bastion ELB, K8s Master(s) & Node(s)
- Revoke default outbound traffic which is open to everything
**Limit ACS k8s Master Outbound traffic**
- Add Master node outbound traffic same as inbound traffic 
- Revoke default outbound traffic which is open to everything
**Limit ACS k8s Node Outbound traffic**
- Add Node outbound traffic same as inbound traffic
- Add Node outbound to pull images from DockerHub
- Revoke default outbound traffic which is open to everything
**Limit API ELB SG Outbound traffic**
- Add API ELB outbound traffic only to instances it listen (Master SG)
- Revoke …
> REPO-3534: Security Group Outbound traffic

- docs/helm-deployment-aws_cloud.md
- docs/k8s-pod-security-policies.md
I would like to remove the wiki page: https://github.com/Alfresco/acs-deployment/wiki/Apply-PSP
And add the documentation to the /docs folder.
> REPO-3576 Move and enhance PSP doc

- helm/alfresco-content-services/templates/ingress-repository.yaml
- Repo Ingress controller to follow HTTP -> HTTPS redirection (by default)
> Enable SSL Redirect on Repo Ingress Controller for http -> https redirection

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/templates/config-share.yaml
docker-compose : Add external alfresco.host and alfresco.port to JAVA_OPTS for repository image in order to fix AOS
docker-compose : Add external aflresco.host alfresco.port alfresco.context and alfresco.protocol to JAVA_OPTS for share image in order to fix broken admin console link
helm : Add CATALINA_OPTS to config-share. Add alfresco.proxy value to fix broken admin console link
> REPO-3721: Admin console link

- README.md
- docker-compose/docker-compose.yml
- docs/docker-compose-deployment.md
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
* REPO-3747: Update comments with instructions on getting an extended trial
* REPO-3747: Update README.md
* REPO-3747: Added Enterprise license prerequisite
Enterprise license is a prerequisite for any serious trial.
Added details on how to apply the license.
Added links for license upload and Share.
* REPO-3747: Trial license prerequisite
(cherry picked from commit f63f31d526e06a40e08f1b02543fb747ce7e5e78)
> REPO-3747 update trial license usage info (#70)

- docker-compose/docker-compose.yml
- docs/docker-compose-deployment.md
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
* The written instructions made in the original commit have been updated on the support/HF/1.0 branch, this cherry-pick brings those updates to the master branch
(cherry picked from commit 71320ba5d93a9064d0359a3572b0ed08fc97aa3a)
> REPO-3747 update trial license usage info (#70) (#71)

- docs/helm-deployment-aws_cloud.md
This is to address MNT-20007: "alfresco-docker-base-tomcat sets cookie secure
flag to true, requiring https for cookies to be transmitted"
> REPO-3832: Update docs to recommend HTTPS

- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/config-transform-router.yaml
DBP chart brings its own Alfresco Infrastructure. So when we bring in the ACS chart we disable the requirement to bring another Infrastructure Chart. 
We need a default for message broker URL property to pick up the ActiveMq service that comes with DBP's Alfresco Infrastructure.
> DEPLOY-563: Stable Infrastructure Chart for ACS 6.1 (with ActiveMQ)

- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/config-transform-router.yaml
DBP chart brings its own Alfresco Infrastructure. So when we bring in the ACS chart we disable the requirement to bring another Infrastructure Chart.
We need a default for message broker URL property to pick up the ActiveMq service that comes with DBP's Alfresco Infrastructure.
> Deploy 563: Stable Infrastructure Chart for ACS 6.1 (with ActiveMQ)

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/values.yaml
- update alfresco-content-repository and alfresco-share image for 6.1.0-RC1 release
> REPO-3934: ACS 6.1: Release RC1

- docker-compose/docker-compose.yml
As per requests:
* move ADW to the "/workspace" root (see https://issues.alfresco.com/jira/browse/ACE-5900)
* expose ACS via the "/"
* remove old comments from the docker-compose
> ACE-5900: move ADW to the "/workspace" route

- docker-compose/docker-compose.yml
Set `127.0.0.1` as `share.host` to cover the case when 127.0.0.1 is not mapped to `localhost`.
> REPO-4111 / ACE-5920: URL for Share in Admin web page

- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-imagemagick.yaml
- helm/alfresco-content-services/templates/deployment-libreoffice.yaml
- helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
- helm/alfresco-content-services/templates/deployment-tika.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
- helm/alfresco-content-services/values.yaml
- update replicaCount from 1 to 2 for T-Router and T-Engines
- keep only 1 replica for Shared File Store (in case EFS is not enabled)
- update pod scheduling for different Availability Zones and K8s nodes
> ATS-216: Update helm chart reference deployment (on k8s) with 2 replicas

- helm/alfresco-content-services/templates/Rule_04-network-policy-repository.yaml
- helm/alfresco-content-services/templates/Rule_05-network-policy-search.yaml
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/ingress-repository.yaml
- helm/alfresco-content-services/values.yaml
Add external host and port for search in values.yaml
If alfresco-search chart is not enabled, add if-else-end clause to config-repository.yaml to skip adding solr.host and solr.port from alfresco-search charts (null value)
If alfresco-search chart is not enabled, add if-else-end clause to config-repository.yaml to add external values (if uncommented)
If alfresco-search chart is not enabled, disable ingress trafic restriction to */solr/*
If alfresco-search chart is not enabled, disable search network policy
If alfresco-search chart is not enabled, disable trafic from in-cluster search pod.
> REPO-4145 : Helm Chart does not start if alfresco-search is disabled

- docs/helm-deployment-minikube.md
Fixes issue with the repository addresses that was causing an error when running `helm dependency update` command later in the article.
> update minikube tutorial

- helm/alfresco-content-services/ai-reference-values.yaml
Update the AI reference values (image tags) with:
- **alfresco-content-repository-aws:6.1.0.2**
_and_
- **alfresco-share-aws:6.1.0.1**
> ATS-380 : Update AWS image tags for the AI 1.0.0 amps

- helm/alfresco-content-services/templates/ingress-repository.yaml
- helm/alfresco-content-services/templates/ingress-share.yaml
- helm/alfresco-content-services/values.yaml
allows customising the annotations on the ingress of repository and share if required, for example to enable cors
> add support for extra ingress annotations

- docs/helm-deployment-aws_kops.md
- helm/alfresco-content-services/templates/NOTES.txt
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/config-share.yaml
This PR fixes repository and share configs to support templated externalHost, externalPort, externalProtocol custom values required for AAE 7.1 deployment
> fix: use templated external* values for repository and share configs

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/values.yaml
- to use new T-Engines 2.1.0-EA4 / T-Router 1.1.0-EA2
> ATS-473 / ATS-474: Update ACS deployment for ATS (targeting 6.2.0-A2 or higher)

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/requirements.yaml
- helm/alfresco-content-services/templates/NOTES.txt
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/values.yaml
- test/postman/docker-compose/acs-test-docker-compose-collection.json
- test/postman/helm/acs-test-helm-collection.json
- included sync service 3.1.2-RC2 in the docker-compose.yaml.
- included the sync service chart (1.0.0-RC1) as a dependency in the requirements.yaml file.
- in requirements.yaml allowed parent chart to view properties from the child sync chart by importing props found under 'syncservice'.
The ACS chart needs the following property from the sync chart: .Values.syncservice.service.externalPort.  The usage can be seen in config-repository.yaml
- added two postman tests, one for the docker-compose and one for the helm chart. The tests verify that the sync healtheck returns 200.
- updated sync service to use ACS's postgres database in docker-compose.yml
- Recalculated the min memory requirements for the entire docker-compose stack rezulting in ~13GB.
- Removed some obsolete docs regarding …
> APPSREPO-656 : ACS Deployment includes Sync service

- helm/alfresco-content-services/templates/NOTES.txt
Small fix in NOTES.txt to skip defining some variables when Sync service is disable.
> Don't execute sync service specific logic if it is disabled, in NOTES.txt

- docker-compose/docker-compose.yml
Renames `BASEPATH` to `BASE_PATH`
depends on https://github.com/Alfresco/alfresco-content-app/pull/1185
> [ACA-2713] update "base path" variable name

- helm/alfresco-content-services/requirements.yaml
- helm/alfresco-content-services/templates/NOTES.txt
- helm/alfresco-content-services/templates/config-repository.yaml
- Removed references of Sync service externalPort, Sync service will be accesed only though the nginx proxy, there's no need for the ACS parent chart to know the Kubernetes Service port
> REPO-4620 : ACS Chart Forces Declaration of Sync Values

- docs/helm-deployment-aws_kops.md
- helm/alfresco-content-services/requirements.yaml
- modified helm-deployment-aws_kops by:
-> adding a table of contents
-> adding instructions to create a NFS client provisioner
-> updating the ACS install steps to use the latest alfresco-infrastructure chart that supports dynamic provisioning
> REPO-4523 : Use dynamic provisioning to create Persistent Volumes

- helm/alfresco-content-services/values.yaml
- note: master will be updated again soon to AIS 1.1.0-RC1 or higher (see ATS-547)
- this specific change will be cherry-picked to support/SP/2.N (for ACS 6.1.1)
> ATS-462: Update ACS Helm Deployment from AIS 1.0.1 to 1.0.2 (for ACS 6.1.1)

- docs/helm-deployment-aws_kops.md
- docs/use-cases/acs-deployment-with-external-database-kops.md
- docs/use-cases/acs-deployment-with-s3-connector-kops.md
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/requirements.yaml
- helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-imagemagick.yaml
- helm/alfresco-content-services/templates/deployment-libreoffice.yaml
- helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/deployment-share.yaml
- helm/alfresco-content-services/templates/deployment-tika.yaml
- helm/alfresco-content-services/templates/deployment-transform-misc.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
- helm/alfresco-content-services/values.yaml
- helm/deploy-acs-with-ai.sh
- Defined a new `global` variable called `alfrescoRegistryPullSecrets` in ACS parent and child helm chart and updated chart versions
- These changes are made for ACS Helm chart version 6.2
> REPO-4569: Use registryPullSecrets as a global value for parent and child Alfresco Helm charts

- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-imagemagick.yaml
- helm/alfresco-content-services/templates/deployment-libreoffice.yaml
- helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/deployment-share.yaml
- helm/alfresco-content-services/templates/deployment-tika.yaml
- helm/alfresco-content-services/templates/deployment-transform-misc.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
This PR fixes https://issues.alfresco.com/jira/browse/MNT-21041
Added checksum annotation to deployment templates in order to trigger pod restart on any changes in config map values when running `helm upgrade` command, i.e.	
deployment-share.yaml:
```
spec:	
template:	
metadata:	
annotations:	
checksum/config: {{ include (print $.Template.BasePath "/config-share.yaml") . | sha256sum }}	
```
deployment-repository.yaml	
```
spec:	
template:	
metadata:	
annotations:	
checksum/config: {{ include (print $.Template.BasePath "/config-repository.yaml") . | sha256sum }}	
```	
Resolition: Helm upgrade will trigger pod restart when any configurations values in config map  have changed.
> fix(MNT-21041): added checksum annotations for configmaps

- helm/alfresco-content-services/requirements.yaml
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-imagemagick.yaml
- helm/alfresco-content-services/templates/deployment-libreoffice.yaml
- helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/deployment-share.yaml
- helm/alfresco-content-services/templates/deployment-tika.yaml
- helm/alfresco-content-services/templates/deployment-transform-misc.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
- #278 
- Enhance the PR by covering secrets (i.e. if passwords or aws access key/secrets are changed then it should trigger a new repository pod with updated credentials).
> REPO-4916 MNT-21041: ACS Helm upgrade to update configuration values does not restart affected pods

- helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-imagemagick.yaml
- helm/alfresco-content-services/templates/deployment-libreoffice.yaml
- helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/deployment-share.yaml
- helm/alfresco-content-services/templates/deployment-tika.yaml
- helm/alfresco-content-services/templates/deployment-transform-misc.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
This PR fixes https://issues.alfresco.com/jira/browse/MNT-21042
repository-deployment.yaml  
```
spec:   
replicas: {{ .Values.repository.replicaCount }}  
strategy: 
type: RollingUpdate 
rollingUpdate:  
maxSurge: {{ .Values.rollingUpdateMaxSurge | default 1 }} 
maxUnavailable: {{ .Values.rollingUpdateMaxUnavailable | default 0 }}     
template: 
metadata:   
containers:   
- name: {{ .Chart.Name }}   
lifecycle:    
preStop:    
exec: 
command: ["/bin/bash", "-c", "sleep 20"]    
```
Resolution: Rolling update starts  new pod and initiates old pod shutdown only after existing connections are drained to achieve zero donwtime update
> fix(MNT-21042): added rollingUpdate values with sensible defaults

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/requirements.yaml
- helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-imagemagick.yaml
- helm/alfresco-content-services/templates/deployment-libreoffice.yaml
- helm/alfresco-content-services/templates/deployment-pdfrenderer.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/deployment-share.yaml
- helm/alfresco-content-services/templates/deployment-tika.yaml
- helm/alfresco-content-services/templates/deployment-transform-misc.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
- helm/alfresco-content-services/values.yaml
- #279 
- Parameterise `strategy` annotation's `type` option for Repository deployment as `Recreate`
- `rollingUpdate` are defined as global parameters to enable Alfresco dependent helm charts can inherit values when ACS helm chart is updated.
> MNT-21042: ACS Helm upgrade fails to perform rolling update with zero downtime

- README.md
- helm/alfresco-content-services/requirements.yaml
- Bump `alfresco-sync-service` chart version to `3.0.2`
Helm k8 annotation error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "terminationGracePeriodSeconds" in io.k8s.api.core.v1.Container
```
> REPO-4977: Helm client version 3.x is not compatible with ACS helm charts

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/values.yaml
- T-Router 1.2.0-A2 with T-Engines 2.2.0-A5
- change to single CORE_AIO_URL (ATS-736)
> ATS-739: Update ACS Deployment to ATS 1.2.0-A2

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/values.yaml
- ATS-708: Bump to T-Core/T-Engines 2.2.0
- ATS-709: Bump to ATS 1.2.0-RC1 (T-Service/T-Router)
> ATS-708 / ATS-709: Update to ATS 1.2.0-RC1 & T-engines to 2.2.0

- helm/alfresco-content-services/templates/NOTES.txt
After runnig `helm install alfresco-incubator/alfresco-content-services...` a list of URL's is listed and ADW url is not present in that list, but it is deployed. I have added that line in NOTES.txt file
> ACS-112: Added ADW url to notes

- helm/alfresco-content-services/values.yaml
The inclusion of alfresco-infrastructure adds an unwanted nginx-ingress, this can be verified with:
`helm template helm/alfresco-content-services | grep nginx-ingress-controller`
this PR disables its inclusion
> ACS-221 remove ingress from infra

- docker-compose/docker-compose.yml
- docs/use-cases/acs-deployment-with-custom-metadata-keystore.md
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/secret-metadata-keystore.yaml
- helm/alfresco-content-services/values.yaml
This PR provides default config for metadata keystore. 
See also https://github.com/Alfresco/acs-packaging/pull/999
Please note that the documentation https://docs.alfresco.com/6.2/concepts/alf-keystores.html still needs to be updated.
> SEARCH-1915 Metadata keystore configuration

- helm/alfresco-content-services/templates/deployment-filestore.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/values.yaml
This PR enables to externalize init containers Docker image repository and tag values for repository and filestore deployments. This is needed to be able to override values for ACS deployments that use organization's private Docker registry instead of public Docker Hub or Quay.io.
Related PRs:  https://github.com/Alfresco/alfresco-activemq-deployment/pull/9 and https://github.com/Alfresco/alfresco-search-deployment/pull/42
> fix: externalize initContainer Docker image repository and tag

- helm/alfresco-content-services/values.yaml
Following info on ACS-91 and feedback from Abdul, set networkpolicysetting: enabled: to false.
> ACS-91: Disable network policy setting in helm chart

- helm/alfresco-content-services/ai-reference-values.yaml
- helm/alfresco-content-services/values.yaml
- values.yaml & ai-reference-values.yaml
- note: requires ATS (T-Router) 1.3.0-A2 (or higher)
> ATS-761: Bump to AIS 1.2.0-A1

- helm/alfresco-content-services/values.yaml
- note: requires ATS (T-Router) 1.3.0-RC1 (or higher)
> ATS-786: Bump to AIS 1.2.0-RC1

- helm/alfresco-content-services/ai-reference-values.yaml
- helm/alfresco-content-services/values.yaml
- note: also bump ai-reference-values.yaml although these depend on builds for:
-- ACS Packaging
-- Share
> ATS-774: Bump AI T-Engine to final AIS 1.2.0 (for k8s)

- README.md
- docs/docker-compose-deployment.md
- helm/alfresco-content-services/README.md
The only available method of obtaining a 30-day license for docker-compose is through the “ACS Download Trial” web page.
> DOCS-5951 Remove Download Trial license link

- helm/alfresco-content-services/values.yaml
- AIS service pack - targeting ACS 6.2.2 (as part of S/H release train)
> ATS-808: Bump AIS T-Engine to 1.2.1-RC1

- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/values.yaml
I would like to have the capability to add additional volumes and volume mounts to the repository. To do this, I have added an option to add extraVolumes and extraVolumeMounts to the repository without being limited to the pre-defined list.
Kindly let me know if you have any questions or concerns with this update.
Thanks,
Vijay
> Add extra volumes and volumemounts

- docs/docker-compose/README.md
- docs/docker-compose/examples/installing-amps.md
Example documentation on how to install amps into custom images for alfresco-content-repository and alfresco-share images.
Installing AMP's is a very common process and unless you know how to do this in a containerised fashion, it can be challenging.
These examples provides one mechanism that customers can use to install amps when they are using docker-compose. 
Currently there is no other documentation that provides this information.
> MNT-21816 added-installing-amps-examples

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/6.0.N_values.yaml
- helm/alfresco-content-services/6.1.N_values.yaml
- helm/alfresco-content-services/6.2.N_values.yaml
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/values.yaml
Added new keystore props to the helm deployments, also altered the values files for older version but kept the metadata pass and key pass configurable and secured with secrets
> OPSEXP-555: keystore additions

- docker-compose/6.0.N-docker-compose.yml
- docs/helm/docker-desktop-deployment.md
- docs/helm/eks-deployment.md
- helm/alfresco-content-services/charts/alfresco-search/templates/deployment.yaml
- helm/alfresco-content-services/charts/alfresco-search/values.yaml
- Changed default memory limits for search to 2G
- Also changed the URL to use for the liveness probe
- Fixed startup issue in 6.0.N docker compose
- Updated DfD guide to reduce the search memory
> OPSEXP-592: Fix SOLR issues

- helm/alfresco-content-services/6.0.N_values.yaml
- helm/alfresco-content-services/6.1.N_values.yaml
- helm/alfresco-content-services/6.2.N_values.yaml
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/templates/config-ai-transformer.yaml
- helm/alfresco-content-services/templates/config-email.yaml
- helm/alfresco-content-services/templates/config-transformer-routes.yaml
- helm/alfresco-content-services/templates/deployment-ai-transformer.yaml
- helm/alfresco-content-services/templates/svc-ai-transformer.yaml
- helm/alfresco-content-services/values.yaml
Bitnami helm chart is expecting different values for extra posgresql configuration ->
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L201
> OPSEXP-599: db max_connections not taken into consideration

- .travis.yml
- docker-compose/6.2.N-docker-compose.yml
- docs/helm/docker-desktop-deployment.md
- docs/helm/eks-deployment.md
- helm/alfresco-content-services/6.2.N_values.yaml
- helm/alfresco-content-services/requirements.yaml
- helm/alfresco-content-services/templates/ingress-share.yaml
- added share ingress cookie
- edited docs and Travis to pin ingress-nginx chart version to 3.7.1
- added local charts to requirements to fix helm 3.41 linting
> OPSEXP-130: Share ingress setup + pin ingress-nginx version

- docker-compose/6.0.N-docker-compose.yml
- docker-compose/6.1.N-docker-compose.yml
- docker-compose/6.2.N-docker-compose.yml
- helm/alfresco-content-services/6.0.N_values.yaml
- helm/alfresco-content-services/6.1.N_values.yaml
- helm/alfresco-content-services/6.2.N_values.yaml
We should NOT be using hotfix versions in our reference deployments according to our policy.
NOTE: There is no "6.0.1" tag for the repository available so I've updated to the latest hotfix for the 6.0.N deployment.
> OPSEXP-613: Revert artefacts to SP versions

- docker-compose/6.2.N-docker-compose.yml
- docker-compose/docker-compose.yml
- helm/alfresco-content-services/6.2.N_values.yaml
- helm/alfresco-content-services/values.yaml
- note: 2.0.0-adw (rather than 2.0.0)
- note: both master (7.0.0-Mx) *and* 6.2.N since new ADW / OOI extension targets ACS 6.2.2 or higher
> Bump to ADW 2.0.0

- helm/alfresco-content-services/6.0.N_values.yaml
- helm/alfresco-content-services/6.1.N_values.yaml
- helm/alfresco-content-services/6.2.N_values.yaml
- helm/alfresco-content-services/templates/config-dev-log4j-properties.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/values.yaml
Created mechanism to allow custom repo debugging configuration to be provided for the ACS helm charts via values files.
> OPSEXP-664: Allow custom repo debugging configuration to be provided for the ACS helm charts

- docker-compose/6.1.N-docker-compose.yml
- docker-compose/6.2.N-docker-compose.yml
- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
- helm/alfresco-content-services/templates/ingress-share.yaml
- test/postman/docker-compose/acs-test-docker-compose-collection.json
- test/postman/helm/acs-test-helm-collection.json
Updated to new version of alfresco-acs-nginx that now supports Enterprise and Community and includes the required change.
Added additional tests for the extra protected URLs.
> OPSEXP-755 & OPSEXP-756: Update nginx config

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/values.yaml
NOTE: Community remains at 7.0.0-M3 as only stable Share images are pushed to dockerhub.
> Upgrade share for Enterprise deployments

- helm/alfresco-content-services/templates/config-email.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/svc-email.yaml
- helm/alfresco-content-services/templates/svc-repository.yaml
- It should create TCP ELB only if `email.inbound.enabled` (along with `email.server.enabled`)
> Create ELB for TCP services only if email inbound is enabled

- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/values.yaml
Replaced _imageTag_ with image.tag as referred in bitnami charts. Also, 13.1 tag doesn't exists in bitnami's docker repository, but they do have 13.1.0
> OPSEXP-827: ACS Helm deployment is still using Postgres 11 despite being configured with 13

- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/values.yaml
Reverts Alfresco/acs-deployment#520
> Revert "OPSEXP-827: ACS Helm deployment is still using Postgres 11 despite being configured with 13"

- helm/alfresco-content-services/6.1.N_values.yaml
- helm/alfresco-content-services/6.2.N_values.yaml
- helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
- helm/alfresco-content-services/charts/alfresco-search/values.yaml
- helm/alfresco-content-services/charts/alfresco-sync-service/templates/ingress.yaml
- helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/templates/ingress-ooi-service.yaml
- helm/alfresco-content-services/templates/ingress-repository.yaml
- helm/alfresco-content-services/templates/ingress-share.yaml
- helm/alfresco-content-services/values.yaml
This PR makes it possible to configure the TLS section of the Ingress for the following components:
- apiexplorer
- repository
- search
- share
- sync-service
The configuration follows the structure in the default Helm templates (`helm create <name>`):
```yaml
ingress:
tls: []
```
I added an example configuration in values.yaml and community_values.yaml
> Add ability to configure TLS section

- docs/helm/examples/with-ms-teams.md
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/config-ms-teams-service.yaml
- helm/alfresco-content-services/values.yaml
- make sure alfresco.base-url (eg. https://my-env:443) is also configurable
- used to generate ADW preview links (in addition to Alfresco REST API calls)
> ACS-1870: Add MS Teams option to ACS Helm charts (part 2)

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/values.yaml
- from 0.4.0-A1 to 1.0.0-A2 (inc README for pre-commit hook for Helm Docs)
> ACS-1953: Bump MS Teams Int version (helm chart value)

- .travis.yml
- docs/helm/eks-deployment.md
This PR allow for deploying on EKS 1.21 with the newer aws-efs-csi-driver (deployed as part of the cluster installation instead of the nfs-client-provisionner).
The goal is to:
* Stop using the alfresco-volume-claim for postgresql related services
* using dynamic PVC
* rely on the gp2 storageClass for automatic provisioning that's compatible with the service. 
Ref. OPSEXP-1095
> OPSEXP-1095 csi driver update

- docker-compose/docker-compose.yml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/charts/alfresco-sync-service/README.md
- helm/alfresco-content-services/charts/alfresco-sync-service/values.yaml
- helm/alfresco-content-services/values.yaml
Update sync-service image tag for Maidenhead release train
Ref. DESKTOPAPP-853
> DESKTOPAPP-853: Bump sync-service from 3.5.0-M1 to 3.5.0-A4

- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
Changed default solr **SECURE COMMS** from **NONE** to **SECRET**. We need to set the shared secret value for both alfresco `-Dsolr.sharedSecret` and solr `-Dalfresco.secureComms.secret` (default value is “secret”).
> [ACS-2564] update docker-compose and community-docker-compose to use solr with secureComms=secret

- .travis.yml
- docs/helm/docker-desktop-deployment.md
- docs/helm/eks-deployment.md
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/ingress-repository.yaml
- helm/alfresco-content-services/templates/ingress-share.yaml
- helm/alfresco-content-services/values.yaml
Updates `ingress-nginx` to 4.x in order to support k8s 1.22 so that the build will work also when EKS 1.22 is released.
Applies missing `kubernetes.io/ingress.class: nginx` on ADW that with `ingress-nginx` 3.x was working anyway but not 4.x.
Disable the creation of an IngressClass resource with `--set controller.ingressClassResource.enabled=false` which is new in 4.x and breaks multiple installations per namespace as the IngressClass resource itself is not namespaced and not needed for our configuration.
Update activiti-common to 7.2.0 which includes the ingress API changes for 1.22 for ADW
Ref. OPSEXP-1339 OPSEXP-1348
> OPSEXP-1339 Update ingress-nginx to 4.x for k8s 1.22

- helm/alfresco-content-services/templates/_helpers-ingress.tpl
- helm/alfresco-content-services/templates/ingress-repository.yaml
- helm/alfresco-content-services/templates/ingress-share.yaml
In some circumstances the nginx ingress annotations generated broken configuration preventing ingress controller from working. This seem to happen even more often with ingress-nginx v4
This PR prevents that by moving the configuration-snippet to server-snippet and making sure it can't be overridden by annotations from values.
> OPSEXP-1378: USe server-snippet to avoid nested location within exact matches

- helm/alfresco-content-services/templates/config-ai-transformer.yaml
pipeline failing with:
```
Synchronization of release 'acs' in namespace 'acs' failed: installation failed: YAML parse error on alfresco-content-services/templates/config-ai-transformer.yaml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
```
> OPSEXP-1574 Fixup for broken ai-transformer config

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/values.yaml
- from 1.1.2 to 1.1.3-A1 (ready for code freeze)
- note: once we release final 1.1.3 (GA) then we will bump again
> ACS-3180: Bump MS 365/OneDrive "sample" (helm chart)

- helm/alfresco-content-services/charts/alfresco-sync-service/templates/deployment-syncservice.yaml
- helm/alfresco-content-services/templates/deployment-transform-router.yaml
When performing a helm upgrade over an existing deployment helm would error with; 
client.go:205: [debug] error updating the resource "alfresco-content-services-alfresco-router":
failed to create patch: map: map[] does not contain declared merge key: name
upgrade.go:355: [debug] warning: Upgrade "alfresco-content-services" failed: failed to create patch: map: map[] does not contain declared merge key: name
This is because the original deployment would set the imagePullSecret to "name: " and would try to be re-set at upgrade. Since a blank value is defaulted in the chart values this conditional is needed in all the deployment (and is present in the others).
> Fix imagePullSecret handling when secret is not set

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/_helpers-elasticsearch.tpl
- helm/alfresco-content-services/values.yaml
OPSEXP-1665
We can have computed values when generating templates in the main chart but not for values that needs to be provided to a subchart. I revert to having es connection defaults for embedded elasticsearch that is the default.
> OPSEXP-1665 Fixup default values when using embedded elasticsearch

- .pre-commit-config.yaml
- docker-compose/elasticsearch-override-docker-compose.yml
- docs/docker-compose/README.md
OPSEXP-1717
Test with:
```
docker-compose -f docker-compose.yml -f elasticsearch-override-docker-compose.yml up -d
```
> OPSEXP-1717 Add Elasticsearch connector to docker-compose

- .github/workflows/verify.yml
Changes addressing https://github.com/Alfresco/acs-deployment/actions/runs/3095790240
> OPSEXP-1545 Fix workflow for forked PRs

- helm/alfresco-content-services/templates/config-repository.yaml
previous change seem to break fluxcd helm-operator for whatever reason.
```
Warning  FailedReleaseSync  25m (x4 over 21h)    helm-operator  synchronization of release 'acs' in namespace 'acs' failed: failed to prepare chart for release: no cached repository for helm-manager-73205d3bb7f8cb7f05718c543008b393734fbfa7f524827aa27edb8da704707e found. (try 'helm repo update'): error loading /root/.cache/helm/repository/helm-manager-73205d3bb7f8cb7f05718c543008b393734fbfa7f524827aa27edb8da704707e-index.yaml: no API version specified
Warning  FailedReleaseSync  92s (x303 over 15h)  helm-operator  synchronization of release 'acs' in namespace 'acs' failed: dry-run upgrade failed: dry-run upgrade for comparison failed: parse error at (alfresco-content-services/templates/config-repository.yaml:42): …
```
> OPSEXP-1766 Fixup helm deployment error

- .github/workflows/helm-community.yml
Fix for random:
```
Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "[https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s](https://ingress-nginx-controller-admission.ingress-nginx.svc/networking/v1/ingresses?timeout=10s)": dial tcp 10.96.190.34:443: connect: connection refused
```
https://github.com/Alfresco/acs-deployment/actions/runs/3330378271/jobs/5508815454#step:6:26
> wait for nginx-ingress during community workflow

- .github/workflows/helm-community.yml
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/tests/repository_test.yaml
```
2022-10-14 14:40:09,598 ERROR [org.alfresco.repo.search.impl.elasticsearch.contentmodelsync.ElasticsearchIndexServic
e] [elasticsearch-initializer] Failed to check if basic mapping is loaded on alfresco
java.io.IOException: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:884)
```
OPSEXP-1812
> OPSEXP-1812 Fix for missing trustAnchors in repository deployment

- .github/actions/charts-as-json/action.yml
- .github/workflows/helm-enterprise.yml
OPSEXP-1828
https://github.com/Alfresco/alfresco-build-tools/pull/163
> OPSEXP-1828 Use the correct values file during helm enterprise tests

- .github/workflows/docker-compose-community.yml
- .github/workflows/docker-compose-enterprise.yml
- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- .github/workflows/helm-release.yml
- .github/workflows/pre-commit-compose.yml
- .github/workflows/pre-commit-helm-docs.yml
Ref: OPSEXP-1761
Ref: https://github.com/Alfresco/alfresco-build-tools/pull/210
Also unset concurrency limits 
[OPSEXP-1761]: https://alfresco.atlassian.net/browse/OPSEXP-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OPSEXP-1761: Bump Alfresco/alfresco-build-tools from 1.26.0 to 1.28.0

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/charts/alfresco-search/README.md
- helm/alfresco-content-services/charts/alfresco-search/templates/ingress.yaml
- helm/alfresco-content-services/charts/alfresco-search/templates/secrets.yaml
- helm/alfresco-content-services/charts/alfresco-search/tests/ingress_test.yaml
- helm/alfresco-content-services/charts/alfresco-search/tests/secret_test.yaml
- helm/alfresco-content-services/charts/alfresco-search/tests/values/ingress.yaml
- helm/alfresco-content-services/charts/alfresco-search/values.yaml
- helm/alfresco-content-services/values.yaml
Ref: OPSEXP-1651
[OPSEXP-1651]: https://alfresco.atlassian.net/browse/OPSEXP-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OPSEXP-1651 support existing secret for search ingress

- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/_helpers-elasticsearch.tpl
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/liveindexing-deployment.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/secret-elasticsearch.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/liveindexing_test.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/reindexing_test.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/secret-elasticsearch_test.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/secret_test.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
Ref: OPSEXP-1651
[OPSEXP-1651]: https://alfresco.atlassian.net/browse/OPSEXP-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OPSEXP-1651 Use secret to configure elasticsearch credentials

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/README.md
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/templates/reindexing-job.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/tests/reindexing_test.yaml
- helm/alfresco-content-services/charts/alfresco-elasticsearch-connector/values.yaml
- helm/alfresco-content-services/templates/deployment-repository.yaml
- helm/alfresco-content-services/templates/secret-database.yaml
- helm/alfresco-content-services/tests/secret-database_test.yaml
- helm/alfresco-content-services/values.yaml
> OPSEXP-1651 Use existing secret to configure ACS postgres credentials

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/charts/activemq/Chart.yaml
- helm/alfresco-content-services/charts/activemq/README.md
- helm/alfresco-content-services/charts/activemq/README.md.gotmpl
- helm/alfresco-content-services/charts/activemq/templates/deployment-activemq.yaml
- helm/alfresco-content-services/charts/activemq/tests/deployment-activemq_test.yaml
- helm/alfresco-content-services/charts/activemq/values.yaml
- helm/alfresco-content-services/templates/secret-message-broker.yaml
- helm/alfresco-content-services/values.yaml
OPSEXP-1651
[OPSEXP-1651]: https://alfresco.atlassian.net/browse/OPSEXP-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OPSEXP-1651 Use existing secret to configure activemq credentials in embedded chart

- .github/workflows/helm-community.yml
Fixes:
```
This action is deprecated, use Alfresco/alfresco-build-tools/.github/actions/helm-build-chart instead.
```
https://github.com/Alfresco/acs-deployment/actions/runs/3909451581
> Fix deprecation warning for helm build action

- docs/helm/docker-desktop-deployment.md
- docs/helm/eks-deployment.md
- docs/helm/examples/email-enabled.md
- docs/helm/examples/search-services.md
- docs/helm/examples/with-ai.md
- docs/helm/examples/with-aws-services.md
- docs/helm/examples/with-ms-teams.md
- docs/helm/examples/with-ooi.md
Ref: OPSEXP-1940
Added values apply to deployment of ACS 7.2+
> OPSEXP-1940: add solr/repo tracking secret

- updatecli.d/supported-matrix.yaml
- updatecli.d/uber-manifest.tpl
We forgot about updatecli pipeline that are impacted by the charts' dance
> OPSEXP-1852: fix updatecli after moving search enterprise chart

- docs/helm/values/local-dev-values.yaml
Reusing standard cpu limits since previous values have an heavy impact on pod startup times and it doesn't really improve experience on low-end machine or clusters.
> OPSEXP-1861 Fixup slow filestore startup when using desktop values

- docker-compose/7.0.N-docker-compose.yml
- docker-compose/7.1.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
- docker-compose/7.3.N-docker-compose.yml
- docker-compose/docker-compose.yml
- helm/alfresco-content-services/7.0.N_values.yaml
- helm/alfresco-content-services/7.1.N_values.yaml
- helm/alfresco-content-services/7.2.N_values.yaml
- helm/alfresco-content-services/7.3.N_values.yaml
Changed version of sync-service to 3.9.0 for Oxford release.
> DESKTOPAPP-1615: Bump sync-service to 3.9.0

- .github/workflows/bumpVersions.yml
- .github/workflows/helm-enterprise.yml
- README.md
- helm/alfresco-content-services/7.0.N_values.yaml
- helm/alfresco-content-services/7.1.N_values.yaml
- helm/alfresco-content-services/7.2.N_values.yaml
- helm/alfresco-content-services/7.3.N_values.yaml
- updatecli.d/supported-matrix.yaml
- updatecli.d/uber-manifest.tpl
Updatecli pipeline and workflow.
pipeline:
* add components released during oxford and bump versions
workflow:
* remove the `workflow_dispatch` and the updatecli PR target action
* remove matrix to have a single PR and avoid triggering numerous actions on each commit. Even if we have concurrency only the first commit is built which do not make sense (as we would prefer building the branch in its final state), and we can't cancel job to build only on the last commit other wise we might have leftover releases on acs-cluster.
> OPSEXP-2109: update updatecli

- .github/workflows/helm-community.yml
- test/community-integration-test-values.yaml
see [failure](https://github.com/Alfresco/acs-deployment/actions/runs/5088408110/jobs/9144773299#step:5:11)
This is the same solution I've applied in https://github.com/Alfresco/alfresco-helm-charts/pull/29
Ref: OPSEXP-2109
> OPSEXP-2109 avoid crashloop during community testing

- docker-compose/7.0.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
- docker-compose/7.4.N-docker-compose.yml
- updatecli.d/supported-matrix.yaml
Ref: OPSEXP-2132
tengine-aio component used only in docker compose was missing in updatecli config
no need to release as it was correctly bumped manually for 6.0.0 and the inconsistency was exposed only after https://github.com/Alfresco/acs-deployment/pull/937
> OPSEXP-2132 Properly handle tengine-aio bumping in updatecli

- .github/workflows/pre-commit-compose.yml
- .github/workflows/pre-commit-helm.yml
- .gitignore
- .pre-commit-config.yaml
- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
* Make sure we don't pull newer/untested dependencies
* Fixup failure in the creation of the sync service postgresql pod
```
CreateContainerConfigError (secret "acs-postgresql-syncservice" not found)
```
Requires https://github.com/Alfresco/alfresco-build-tools/pull/273
Ref: OPSEXP-2152
> OPSEXP-2152 Introduce lockfile to avoid dependencies breakage

- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- test/community-integration-test-values.yaml
- test/enterprise-integration-test-values.yaml
> OPSEXP-2222 Migrate helm enterprise to kind

- .github/workflows/bumpVersions.yml
Ref: OPSEXP-2311
Just to run more easily the workflow against a custom alfresco-updatecli branch
> OPSEXP-2311 Provide an input to trigger alternative updatecli ref

- .github/workflows/bumpVersions.yml
- README.md
- updatecli.d/helm-autodiscovery.yaml
> OPSEXP-2311 Add workflow to bump helm deps, update release docs

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
Ref: OPSEXP-2242
bring back env projection support in alfresco-repository
> OPSEXP-2242: bump alfresco-repository chart to 0.1.0-alpha.16

- .github/workflows/pre-commit-helm.yml
- docs/helm/examples/with-aws-services.md
- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/config-infrastructure.yaml
- helm/alfresco-content-services/templates/secret-message-broker.yaml
- helm/alfresco-content-services/templates/secret-search.yaml
- helm/alfresco-content-services/tests/search_test.yaml
- helm/alfresco-content-services/values.yaml
> OPSEXP-2298: fix wrong repository URL in search enterprise reindexing job

- docker-compose/7.0.N-docker-compose.yml
- docker-compose/7.1.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
- docker-compose/7.3.N-docker-compose.yml
- docker-compose/7.4.N-docker-compose.yml
- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
Ref: OPSEXP-2387
This also fixes CVE-2023-46604 in docker compose
> OPSEXP-2387 Ensure latest activemq image is used in docker compose

- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- test/cgroup-v2-workaround-values.yaml
- test/enterprise-integration-test-values.yaml
> OPSEXP-2396 Switch to large hosted runners for helm enterprise

- .github/workflows/helm-community.yml
- helm/alfresco-content-services/community_values.yaml
- test/community-integration-test-values.yaml
Ref: OPSEXP-2403
Exposed from a failure in https://github.com/Alfresco/acs-deployment/pull/1047
> OPSEXP-2403 Fix community workflow not really using community values

- docker-compose/7.2.N-docker-compose.yml
- docker-compose/7.3.N-docker-compose.yml
- docker-compose/7.4.N-docker-compose.yml
- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
- docker-compose/elasticsearch-override-docker-compose.yml
- helm/alfresco-content-services/7.1.N_values.yaml
- helm/alfresco-content-services/7.2.N_values.yaml
- helm/alfresco-content-services/7.3.N_values.yaml
- helm/alfresco-content-services/7.4.N_values.yaml
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/values.yaml
> OPSEXP-2403 Bump tags to fix activemq CVE-2023-46604

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/values.yaml
Ref: OPSEXP-2435
https://github.com/Alfresco/alfresco-helm-charts/releases/tag/alfresco-repository-0.1.2
> OPSEXP-2435 Bump alfresco-repository chart to v0.1.2

- helm/alfresco-content-services/7.1.N_values.yaml
> OPSEXP-2422 Bump intelligence for ACS 7.1 to fix CVE-2023-46604

- .github/workflows/bumpVersions.yml
- .github/workflows/docker-compose-community.yml
- .github/workflows/docker-compose-enterprise.yml
- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- .github/workflows/helm-release.yml
- .github/workflows/helm-static-checks.yml
- .github/workflows/pre-commit-compose.yml
- .github/workflows/pre-commit-helm.yml
- docker-compose/7.0.N-docker-compose.yml
- docker-compose/7.1.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
* Add docker compose enterprise timeout and containers debug
* Add -XX:MaxRAM workaround [ACS containers and cgroup v2 in ACS up to 7.2](https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-containers-and-cgroup-v2-in-acs-up-to-7-2/ba-p/318039)
Ref: OPSEXP-2445
Requires: https://github.com/Alfresco/alfresco-build-tools/pull/478
> OPSEXP-2445 Fix flaky docker compose enterprise tests

- .github/actions/charts-as-json/action.yml
- .github/workflows/helm-enterprise.yml
- helm/alfresco-content-services/linter_values.yaml
It was introduced for the new helmlint pre-commit hook and got well hidden by long job names
Ref: OPSEXP-2439
> OPSEXP-2439 Exclude linter_values.yaml from helm ent workflow

- docs/helm/README.md
- docs/helm/desktop-deployment.md
- docs/helm/kind-deployment.md
We started using KinD for the CI and eventually can be useful to run it locally because it's a more portable K8s than other alternatives (Rancher Desktop, minikube, ...)
Ref: OPSEXP-2439
> OPSEXP-2439 Document how to deploy with KinD

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
Ref: OPSEXP-2488
https://github.com/Alfresco/alfresco-helm-charts/tree/alfresco-repository-0.2.0
> OPSEXP-2488 Bump alfresco-repository chart to v0.2.0

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
> OPSEXP-2443 Bump all charts to support component label

- helm/alfresco-content-services/7.0.N_values.yaml
- helm/alfresco-content-services/7.1.N_values.yaml
- helm/alfresco-content-services/7.2.N_values.yaml
- helm/alfresco-content-services/7.3.N_values.yaml
- helm/alfresco-content-services/7.4.N_values.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/values.yaml
* Latest version is now graviton compatible
* Fix wrong postgres versions used in previous acs versions (7.2, 7.1, 7.0)
Ref: OPSEXP-2487
> OPSEXP-2487 Align postgres versions to supported platforms

- docs/helm/README.md
- docs/helm/examples/with-keycloak.md
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/values.yaml
> OPSEXP-2391 Document how to provision with an external keycloak

- docs/helm/desktop-deployment.md
- docs/helm/ingress-nginx.md
so we can link to it more easily
not sure for the [eks flavour](https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/eks-deployment.md#ingress) what it's really need to be kept so not touching it now unless someone advice
Ref: OPSEXP-2391
> OPSEXP-2391 Move ingress-nginx to a dedicated section

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
> OPSEXP-2488 Bump alfresco connector charts to use stable version of ingress apiVersion and fix extraAnnotations

- .github/workflows/bumpVersions.yml
- .github/workflows/docker-compose-community.yml
- .github/workflows/docker-compose-enterprise.yml
- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- .github/workflows/helm-release.yml
- .github/workflows/helm-static-checks.yml
- .github/workflows/pre-commit-compose.yml
- .github/workflows/pre-commit-helm.yml
- docs/helm/autoscaling.md
- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/templates/config-repository.yaml
- helm/alfresco-content-services/values.yaml
- test/community-integration-test-values.yaml
- test/enterprise-integration-test-values.yaml
> OPSEXP-2526: bump alfresco-repository to allow repo hpa and add tests

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
> OPSEXP-2525 Bump alfresco-transform-service chart to allow hpa

- README.md
- docs/helm/eks-deployment.md
- docs/helm/ingress-nginx.md
- docs/helm/values/letsencrypt_values.yaml
* install ingress-nginx in the quickstart way
* drop external dns in favour of a simple dns creation step
* add cert-manager to generate letsencrypt certs
Ref: OPSEXP-2486
> OPSEXP-2486 Rewrite ingress, dns and https docs for eks deployment

- .github/workflows/helm-enterprise.yml
- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/templates/_helpers-ats.tpl
- helm/alfresco-content-services/templates/config-infrastructure.yaml
- helm/alfresco-content-services/templates/keda/scaler-activemq-ats-im.yaml
- helm/alfresco-content-services/templates/keda/scaler-activemq-ats-lo.yaml
- helm/alfresco-content-services/templates/keda/scaler-activemq-ats-misc.yaml
- helm/alfresco-content-services/templates/keda/scaler-activemq-ats-pdf.yaml
- helm/alfresco-content-services/templates/keda/scaler-activemq-ats-tika.yaml
- test/autoscaling-hpa-test-values.yaml
> OPSEXP-2115: bump charts to add consistent default affinity rules

- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- helm/acs-sso-example/docs/sso-guide.md
> OPSEXP-2590 Use helm build for fetching deps

- README.md
- docker-compose/7.1.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
- docker-compose/7.3.N-docker-compose.yml
- docker-compose/7.4.N-docker-compose.yml
- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
- docs/docker-compose/README.md
- docs/helm/autoscaling.md
- test/postman/docker-compose/acs-test-docker-compose-collection.json
> OPSEXP-2411: switch docker compose proxy to traefik

- docker-compose/7.1.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
- docker-compose/pre-release-docker-compose.yml
- helm/alfresco-content-services/7.1.N_values.yaml
- helm/alfresco-content-services/7.2.N_values.yaml
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/pre-release_values.yaml
- helm/alfresco-content-services/values.yaml
> OPSEXP-2871 Bump tags for Libra release

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
> OPSEXP-2654 Bump search-enterprise to 4.2.0-alpha.0

- .github/kics.yml
- .github/workflows/kics.yml
- docker-compose/7.1.N-docker-compose.yml
- docker-compose/7.2.N-docker-compose.yml
- docker-compose/7.3.N-docker-compose.yml
- docker-compose/7.4.N-docker-compose.yml
- docker-compose/community-docker-compose.yml
- docker-compose/docker-compose.yml
- docker-compose/pre-release-docker-compose.yml
- docker-compose/solr6-override-docker-compose.yml
* Fix privileged requirement due to podman selinux restrictions
* Drop selinux labeling to allow accessing /var/run/docker.sock under podman
* Fix pre-release still including old acs-nginx
* Drop deprecated version tag
* Exclude kics findings for known issues which are fine for testing environments
> OPSEXP-2411 Drop privileged for traefik containers

- .github/workflows/bumpVersions.yml
- updatecli.d/helm-autodiscovery.yaml
requires:
* https://github.com/updatecli/updatecli/pull/2736
tested in https://github.com/Alfresco/acs-deployment/actions/runs/11165106641 (will raise another PR for the actual bump)
> Enable pre-release versions in helm autodiscovery

- helm/alfresco-content-services/7.1.N_values.yaml
- helm/alfresco-content-services/7.2.N_values.yaml
- helm/alfresco-content-services/7.3.N_values.yaml
- helm/alfresco-content-services/7.4.N_values.yaml
- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/templates/config-infrastructure.yaml
- helm/alfresco-content-services/templates/secret-aas-elasticearch.yaml
- helm/alfresco-content-services/values.yaml
- test/community-integration-test-values.yaml
- test/enterprise-integration-test-values.yaml
> OPSEXP-2878 Add alfresco-audit-storage chart

- .github/workflows/docker-compose-community.yml
- .github/workflows/docker-compose-enterprise.yml
- docker-compose/7.1.N-compose.yaml
- docker-compose/7.2.N-compose.yaml
- docker-compose/7.3.N-compose.yaml
- docker-compose/7.4.N-compose.yaml
- docker-compose/community-compose.yaml
- docker-compose/compose.yaml
- docker-compose/pre-release-compose.yaml
> OPSEXP-2253 Add healthchecks and conditional service startup based on service health in docker compose

- docker-compose/compose.yaml
- docker-compose/pre-release-compose.yaml
- alfresco-audit-storage and kibana are in compose.yaml but not pre-release-compose.yaml, so they have been now been added.
- alfresco-audit-storage image is updated to the latest alpha release
- alfresco-elasticsearch-connector image to the latest alpha release
> ACS-8989 Update audit storage and elasticsearch connector versions

- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/values.yaml
> OPSEXP-2902 Enable audit-storage components as default

- .github/workflows/helm-enterprise.yml
- test/autoscaling-hpa-test-values.yaml
> OPSEXP-2938 Drop unreliable HPA test and enable clustered renditions on GA

- .github/workflows/pre-commit-helm.yml
- .pre-commit-config.yaml
- docker-compose/solr6-overrides.yaml
- docs/docker-compose/README.md
> OPSEXP-2961 Disable services for solr6 overrides using reset yaml tag and bump pre-commit repos versions

- helm/alfresco-content-services/Chart.lock
- helm/alfresco-content-services/Chart.yaml
- helm/alfresco-content-services/README.md
> OPSEXP-2991 Bump sync-service chart with ingress fix

- docs/helm/ingress-nginx.md
- docs/helm/kind-deployment.md
Ref: OPSEXP-3005 
https://github.com/kubernetes/ingress-nginx/issues/12618
They changed the behavior of `{"allow-snippet-annotations":"true"}}'` - it seems like it doesn't work anymore
Currently even with this set to true we will get: 
```
* admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: annotation group ServerSnippet contains risky annotation based on ingress configuration
* admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: annotation group ServerSnippet contains risky annotation based on ingress configuration
```
It is required to change it to ` {"annotations-risk-level":"Critical"}}' `
> OPSEXP-3005 Document using specific version of ingress-nginx to avoid breakage

- docs/helm/desktop-deployment.md
- docs/helm/examples/external-hazelcast.md
- docs/helm/examples/with-elasticsearch-auth.md
> OPSEXP-2917 Docs: remove unnecessary Solr shared secret for enterprise

- docker-compose/7.2.N-compose.yaml
- docker-compose/7.3.N-compose.yaml
- docker-compose/7.4.N-compose.yaml
- docker-compose/compose.yaml
- docker-compose/pre-release-compose.yaml
- helm/alfresco-content-services/README.md
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/values.yaml
Avoid using Docker Hub for enterprise flavors of compose/helm.
> Fix enterprise compose/helm not using quay.io for docker images

- docker-compose/7.2.N-compose.yaml
- docker-compose/7.3.N-compose.yaml
- docker-compose/7.4.N-compose.yaml
- docker-compose/compose.yaml
- docker-compose/pre-release-compose.yaml
align sfs volume path in docker compose to: https://github.com/Alfresco/acs-deployment/blob/8d5070d624c2a660b960859852853d48310e465c/helm/alfresco-content-services/values.yaml#L288
Fix #625
> Fix sfs volume path in docker compose

- docker-compose/7.2.N-compose.yaml
- docker-compose/7.3.N-compose.yaml
- docker-compose/7.4.N-compose.yaml
- docker-compose/community-compose.yaml
- docker-compose/compose.yaml
- docker-compose/pre-release-compose.yaml
* Enable restarting the alfresco container without data loss
Now it's possible to run consecutive `compose up` without getting:
```
2025-02-26T14:08:49,603 [] ERROR [repo.admin.ConfigurationChecker] [main] CONTENT INTEGRITY ERROR: System content not found in content store: 'store://2025/2/26/13/49/a07593db-c44b-4edb-b593-dbc44bfedb5e.bin'
2025-02-26T14:08:49,603 [] ERROR [repo.admin.ConfigurationChecker] [main] Ensure that the 'dir.root' property './alf_data' is pointing to the correct data location.
2025-02-26T14:08:49,605 [] WARN  [context.support.XmlWebApplicationContext] [main] Exception encountered during context initialization - cancelling refresh attempt: org.alfresco.error.AlfrescoRuntimeException: 01260036 Ensure that the 'dir.root' property './alf_data' is pointing to the …
```
> OPSEXP-3109 Provide anonymous volumes for alfresco content store and sfs

- docker-compose/7.2.N-compose.yaml
- docker-compose/7.3.N-compose.yaml
- docker-compose/7.4.N-compose.yaml
- docker-compose/compose.yaml
- docker-compose/pre-release-compose.yaml
Forgot to remove them in https://github.com/Alfresco/acs-deployment/pull/1301
OPSEXP-3109
> OPSEXP-3109 Drop unused named volumes in compose

- .github/workflows/helm-enterprise.yml
- test/enterprise-integration-test-values.yaml
Makes test jobs reliable again.
Requires:
* https://github.com/Alfresco/alfresco-build-tools/pull/930
OPSEXP-3069
> OPSEXP-3069 Switch to latest default runners

- .github/workflows/helm-community.yml
- .github/workflows/helm-enterprise.yml
- helm/alfresco-content-services/community_values.yaml
- helm/alfresco-content-services/templates/secret-search.yaml
- helm/alfresco-content-services/tests/search_test.yaml
This PR updates `community_values.yaml` to include a note about the `global.search.sharedSecret`, and that there are three modes of communication, with `secret` mode of communication being the default.
While deploying ACM to EKS, I noticed some pods were crashing when using the `community_values.yaml`. After some investigation, I found that the issue was due to the `sharedSecret` being set to `null`, however, this option was not available in the `community_values.yaml`, and it took some time to find out that this existed - especially for someone trying Alfresco ACM the first time. Hopefully, adding this information to the `community_values.yaml` will save some time for others 😊
> 💅 Fail template on missing 'sharedSecret' when Solr is enabled & uses "secret" to secure communication
